[package]
name = "app_store_api"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = "9.3.0"
openssl = "0.10.66"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
